# Generated by Django 5.2.17 on 2026-09-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(blank=True, help_text="Big number, e.g. '1,059' or '3.8'.", max_length=40)),
                ('metric_label', models.CharField(blank=True, max_length=60)),
                ('is_highlight', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occasion', models.CharField(choices=[('table', 'Table for tonight'), ('party', 'Party or group booking'), ('catering', 'Catering enquiry'), ('feedback', 'Feedback for the kitchen')], default='table', max_length=20)),
                ('guests', models.PositiveIntegerField(default=2)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('kitchen', models.CharField(choices=[('food_palace', 'Food Palace'), ('broasted_king', 'Broasted King'), ('juice_palace', 'Juice Palace')], default='food_palace', max_length=20)),
                ('blurb', models.CharField(blank=True, help_text='One line shown under the category heading.', max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'menu categories',
                'ordering': ['kitchen', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('profile_pic_url', models.URLField(blank=True, help_text='Leave blank to use a generated initial avatar.')),
                ('is_local_guide', models.BooleanField(default=False)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('time_ago', models.CharField(default='a year ago', max_length=40)),
                ('is_edited', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('order_type', models.CharField(blank=True, max_length=40)),
                ('meal_type', models.CharField(blank=True, max_length=40)),
                ('price_range', models.CharField(blank=True, max_length=40)),
                ('food_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('service_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('atmosphere_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews appear on the home page.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=40)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_signature', models.BooleanField(default=False, help_text='Shows a flame mark and appears in Home highlights.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menucategory')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
